feature - getSalesOrder
nebkam/netsuite-restlet-php-sdk pull request #6
Opened 2021-02-05 13:20 UTC by Vodzo

2021-02-08 10:47 UTC, nebkam requested changes

2021-02-08 10:47 UTC, nebkam commented on src/ApiService.php
> +	private function executeGetRequest(string $url, ?array $params = []): string
Već postoji `executeGetPdfRequest` , koji mi deluje da se razlikue jedino u content-type.
Možeš li refaktorizovati tako da bude jedan `executeGetRequest` koji pokriva i PDF sa content-type parametrom?
Mislim da će tako biti preglednije

2021-02-08 11:47 UTC, Vodzo commented on src/ApiService.php
> +	private function executeGetRequest(string $url, ?array $params = []): string
Izmenio :)

2021-02-09 08:42 UTC, nebkam approved these changes
Perfect :+1:

2021-02-09 08:42 UTC, merged